### ISSUE TITLE
Django settings

### ISSUE THREAD

**Issue by dkruk** [dkrukouski/django-rest-start-template#4]
Set up Django settings for different environments.

**Comment by palak-gupta** [comment]
you could maintain environment variables values for different environments in separate .env files and load them into the setting based upon the nature of your current environment. For eg. in case of development have a file named .env.dev and check in your code, if the current environment is development then load variables from this file.

**Comment by dkruk** [comment]
@palak-gupta thank you for the suggestion, but I believe that should be the only `.env` file for one environment.
Also, from my point of view, it is not safe to store environment variables for the production server, on the development server, since there is usually much less attention to the security of these servers.

**Comment by palak-gupta** [comment]
@dkrukouski yeah you could have one .env file for one environment and you are right the production environment variable values should never be stored  while commiting the code. What you could do is have .env file store the variable names with some **default false values** that points out the variable usage only but does not reveal any actual credentials. While setting up the environment you could update the .env file to store actual variables values.

**Comment by palak-gupta** [comment]
But I do want to add, usage of .env file is helpful when you are deploying your code directly on some virtual machine. If you are going to dockerize your code then I would suggest you to directly store the environment based setting as actual environment variables of the system.
